export const categories = [
    {
        id: 1,
        name: 'Pizza',
        image: require('../assets/images/noodlesIcon.png'),
    },
    {
        id: 2,
        name: 'Burger',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 3,
        name: 'Italian',
        image: require('../assets/images/Chinese.png'),
    },
    {
        id: 4,
        name: 'Chinese',
        image: require('../assets/images/Chinese.png'),
    },
    {
        id: 5,
        name: 'Noodles',
        image: require('../assets/images/noodlesIcon.png'),
    },
    {
        id: 6,
        name: 'Sweets',
        image: require('../assets/images/sweetIcon.png'),
    },
];

export const featured = {
    id: 1,
    title: 'Hot and Spicy',
    description: 'Soft and tender fried chicken',
    restaurants: [
        {
            id: 1,
            name: 'Spicy Pizza House',
            image: require('../assets/images/pizzaIcon.png'),
            description: 'Hot and spicy pizzas',
            lng: 38.2145602,
            lat: -85.5324269,
            address: '123 Main Street',
            stars: 4,
            reviews: '4.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Cheesy Garlic Pizza',
                    description: 'Cheesy garlic pizza',
                    price: 10,
                    image: require('../assets/images/pizzaIcon.png'),
                },
                {
                    id: 2,
                    name: 'Pepperoni Pizza',
                    description: 'Spicy pepperoni pizza',
                    price: 12,
                    image: require('../assets/images/pizzaIcon.png'),
                },
                {
                    id: 3,
                    name: 'Veggie Pizza',
                    description: 'Healthy veggie pizza',
                    price: 8,
                    image: require('../assets/images/burgerIcon.png'),
                },
            ],
        },
        {
            id: 2,
            name: 'Burger King',
            image: require('../assets/images/burgerIcon.png'),
            description: 'Delicious burgers',
            lng: 38.2145602,
            lat: -85.5324269,
            address: '456 Second Street',
            stars: 4,
            reviews: '3.8k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Classic Burger',
                    description: 'Juicy beef burger',
                    price: 8,
                    image: require('../assets/images/burgerIcon.png'),
                },
                {
                    id: 2,
                    name: 'Cheese Burger',
                    description: 'Burger with cheese',
                    price: 9,
                    image: require('../assets/images/burgerIcon.png'),
                },
                {
                    id: 3,
                    name: 'Chicken Burger',
                    description: 'Crispy chicken burger',
                    price: 7,
                    image: require('../assets/images/burgerIcon.png'),
                },
            ],
        },
        {
            id: 3,
            name: 'Pasta Palace',
            image: require('../assets/images/Italian.png'),
            description: 'Authentic Italian pasta',
            lng: 38.2145602,
            lat: -85.5324269,
            address: '789 Third Street',
            stars: 5,
            reviews: '2.5k',
            category: 'Italian',
            dishes: [
                {
                    id: 1,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian spaghetti',
                    price: 12,
                    image: require('../assets/images/Italian.png'),
                },
                {
                    id: 2,
                    name: 'Fettuccine Alfredo',
                    description: 'Creamy Alfredo pasta',
                    price: 14,
                    image: require('../assets/images/Italian.png'),
                },
                {
                    id: 3,
                    name: 'Penne Arrabbiata',
                    description: 'Spicy penne pasta',
                    price: 10,
                    image: require('../assets/images/Italian.png'),
                },
            ],
        },
    ],
};
